UPDATE `peppol-smp`.document_types SET internal_id=24 WHERE external_id='BIS04 V2' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=116 WHERE external_id='BIS05 V2' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=129 WHERE external_id='BIS36 - MLR' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=139 WHERE external_id='PEPPOLBIS_01A_2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=152 WHERE external_id='PEPPOLBIS_28A_2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=27 WHERE external_id='PEPPOLBIS_28A_2.0_RESPONSE' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=117 WHERE external_id='BIS05 V2' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=154 WHERE external_id='PEPPOLBIS_30A_2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=158 WHERE external_id='PEPPOLBIS_3_0_BILLING_01_UBL' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=30003 WHERE external_id='PEPPOLBIS_3.0_ORDERING_EO' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=30004 WHERE external_id='PEPPOLBIS_3.0_ORDERING_CA' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=30005 WHERE external_id='PEPPOLBIS_3.0_ORDER_AGREEMENT_CA' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=30008 WHERE external_id='PEPPOLBIS_3.0_DESPATCH_ADVICE_CA' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=30010 WHERE external_id='PEPPOLBIS_3.0_INVOICE_RESPONSE_EO' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=118 WHERE external_id='EHF_INVOICE 2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=88 WHERE external_id='EHF_INVOICE_CREDITNOTE 2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=127 WHERE external_id='EHF_CATALOGUE' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=131 WHERE external_id='EHF_CATALOGUE_RESPONSE' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=130 WHERE external_id='EHF_ORDER' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=128 WHERE external_id='EHF_ORDER_RESPONSE' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=120 WHERE external_id='EHF_INVOICE_CREDITNOTE 2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=121 WHERE external_id='EHF_CREDITNOTE 2.0' AND smp_id=1;
UPDATE `peppol-smp`.document_types SET internal_id=151 WHERE external_id='EHF_30A_1.0' AND smp_id=1;

UPDATE `peppol-smp`.document_types SET internal_id=162 WHERE external_id='162' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=163 WHERE external_id='163' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=164 WHERE external_id='164' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=165 WHERE external_id='165' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=166 WHERE external_id='166' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30 WHERE external_id='30' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=159 WHERE external_id='159' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=29 WHERE external_id='29' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=21 WHERE external_id='21' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=126 WHERE external_id='126' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=121 WHERE external_id='121' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=120 WHERE external_id='120' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=128 WHERE external_id='128' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=127 WHERE external_id='127' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=118 WHERE external_id='118' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=24 WHERE external_id='24' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=84 WHERE external_id='84' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=116 WHERE external_id='116' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=139 WHERE external_id='139' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=83 WHERE external_id='83' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=152 WHERE external_id='152' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=27 WHERE external_id='27' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=157 WHERE external_id='157' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=117 WHERE external_id='117' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=154 WHERE external_id='154' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=167 WHERE external_id='167' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=158 WHERE external_id='158' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=160 WHERE external_id='160' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30003 WHERE external_id='178' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30004 WHERE external_id='180' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30005 WHERE external_id='181' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30006 WHERE external_id='175' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30007 WHERE external_id='172' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30008 WHERE external_id='177' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=176 WHERE external_id='176' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=174 WHERE external_id='174' AND smp_id=2;
UPDATE `peppol-smp`.document_types SET internal_id=30010 WHERE external_id='173' AND smp_id=2;
