const Countries = [
    {code: 'AT', name: 'Austria'},
    {code: 'SK', name: 'Slovakia'},
    {code: 'SI', name: 'Slovenia'},
    {code: 'SE', name: 'Sweden'},
    {code: 'PT', name: 'Portugal'},
    {code: 'PL', name: 'Poland'},
    {code: 'NO', name: 'Norway'},
    {code: 'NL', name: 'Netherlands'},
    {code: 'MT', name: 'Malta'},
    {code: 'HU', name: 'Hungary'},
    {code: 'LV', name: 'Latvia'},
    {code: 'LT', name: 'Lithuania'},
    {code: 'IS', name: 'Iceland'},
    {code: 'IT', name: 'Italy'},
    {code: 'IE', name: 'Ireland'},
    {code: 'GR', name: 'Greece'},
    {code: 'GI', name: 'Gibraltar'},
    {code: 'GB', name: 'United Kingdom'},
    {code: 'FR', name: 'France'},
    {code: 'FI', name: 'Finland'},
    {code: 'ES', name: 'Spain'},
    {code: 'EE', name: 'Estonia'},
    {code: 'DK', name: 'Denmark'},
    {code: 'DE', name: 'Germany'},
    {code: 'CH', name: 'Switzerland'},
    {code: 'BE', name: 'Belgium'},
    {code: 'BG', name: 'Bulgaria'},
    {code: 'HR', name: 'Croatia'}
];

export default Countries;