const IcdValues = [
    {icd: "9922", code: "AD:VAT", name: "Andorra VAT number"},
    {icd: "9923", code: "AL:VAT", name: "Albania VAT number"},
    {icd: "9915", code: "AT:GOV", name: "Österreichisches Verwaltungs bzw. Organisationskennzeichen"},
    {icd: "9919", code: "AT:KUR", name: "Kennziffer des Unternehmensregisters"},
    {icd: "9914", code: "AT:VAT", name: "Österreichische Umsatzsteuer-Identifikationsnummer"},
    {icd: "0151", code: "AU:ABN", name: "Australian Business Number (ABN) Scheme"},
    {icd: "9924", code: "BA:VAT", name: "Bosnia and Herzegovina VAT number"},
    {icd: "9956", code: "BE:CBE", name: "Belgian Crossroad Bank of Enterprises"},
    {icd: "9925", code: "BE:VAT", name: "Belgium VAT number"},
    {icd: "9926", code: "BG:VAT", name: "Bulgaria VAT number"},
    {icd: "0183", code: "CH:UIDB", name: "Swiss Unique Business Identification Number"},
    {icd: "9927", code: "CH:VAT", name: "Switzerland VAT number"},
    {icd: "9928", code: "CY:VAT", name: "Cyprus VAT number"},
    {icd: "9929", code: "CZ:VAT", name: "Czech Republic VAT number"},
    {icd: "9958", code: "DE:LID", name: "German Leitweg ID"},
    {icd: "0204", code: "DE:LWID", name: "Koordinierungsstelle für IT-Standards (KoSIT)"},
    {icd: "9930", code: "DE:VAT", name: "Germany VAT number"},
    {icd: "9901", code: "DK:CPR", name: "Danish Ministry of the Interior and Health"},
    {icd: "9902", code: "DK:CVR", name: "The Danish Commerce and Companies Agency"},
    {icd: "0184", code: "DK:DIGST", name: "DIGSTORG"},
    {icd: "0198", code: "DK:ERST", name: "The Danish Business Authority"},
    {icd: "0096", code: "DK:P", name: "The Danish Commerce and Companies Agency"},
    {icd: "9904", code: "DK:SE", name: "Danish Ministry of Taxation, Central Customs and Tax Administration"},
    {icd: "9905", code: "DK:VANS", name: "Danish VANS providers"},
    {icd: "0060", code: "DUNS", name: "Dun and Bradstreet Ltd"},
    {icd: "0191", code: "EE:CC", name: "Estonia company code"},
    {icd: "9931", code: "EE:VAT", name: "Estonia VAT number"},
    {icd: "9920", code: "ES:VAT", name: "Agencia Española de Administración Tributaria"},
    {icd: "0130", code: "EU:NAL", name: "Directorates of the European Commission"},
    {icd: "9913", code: "EU:REID", name: "Business Registers Network"},
    {icd: "9912", code: "EU:VAT", name: "National ministries of Economy"},
    {icd: "0037", code: "FI:OVT", name: "Finnish tax board"},
    {icd: "0002", code: "FR:SIRENE", name: "INSEE: National Institute for statistics and Economic studies"},
    {icd: "0009", code: "FR:SIRET", name: "DU PONT DE NEMOURS"},
    {icd: "9957", code: "FR:VAT", name: "France VAT number"},
    {icd: "9932", code: "GB:VAT", name: "United Kingdom VAT number"},
    {icd: "0088", code: "GLN", name: "GS1"},
    {icd: "9933", code: "GR:VAT", name: "Greece VAT number"},
    {icd: "9934", code: "HR:VAT", name: "Croatia VAT number"},
    {icd: "9910", code: "HU:VAT", name: "Hungarian Tax Board"},
    {icd: "9918", code: "IBAN", name: "S.W.I.F.T. Society for Worldwide Interbank Financial Telecommunications s.c."},
    {icd: "9935", code: "IE:VAT", name: "Ireland VAT number"},
    {icd: "9917", code: "IS:KT", name: "Icelandic National Registry"},
    {icd: "9917", code: "IS:KT", name: "Icelandic National Registry"},
    {icd: "0196", code: "IS:KTNR", name: "Icelandic National Registry"},
    {icd: "9907", code: "IT:CF", name: "TAX Authority"},
    {icd: "0201", code: "IT:CUUO", name: "Codice Univoco Unità Organizzativa iPA"},
    {icd: "0097", code: "IT:FTI", name: "Ediforum Italia"},
    {icd: "9921", code: "IT:IPA", name: "Indice delle Pubbliche Amministrazioni"},
    {icd: "0142", code: "IT:SECETI", name: "Servizi Centralizzati SECETI"},
    {icd: "0135", code: "IT:SIA", name: "Società Interbancaria per l Automazione"},
    {icd: "9906", code: "IT:VAT", name: "Ufficio responsabile gestione partite IVA"},
    {icd: "0199", code: "LEI", name: "Legal Entity Identifier"},
    {icd: "9936", code: "LI:VAT", name: "Liechtenstein VAT number"},
    {icd: "0200", code: "LT:LEC", name: "State Enterprise Centre of Registers"},
    {icd: "9937", code: "LT:VAT", name: "Lithuania VAT number"},
    {icd: "9938", code: "LU:VAT", name: "Luxemburg VAT number"},
    {icd: "9939", code: "LV:VAT", name: "Latvia VAT number"},
    {icd: "9940", code: "MC:VAT", name: "Monaco VAT number"},
    {icd: "9941", code: "ME:VAT", name: "Montenegro VAT number"},
    {icd: "9942", code: "MK:VAT", name: "Macedonia, the former Yugoslav Republic of VAT number"},
    {icd: "9943", code: "MT:VAT", name: "Malta VAT number"},
    {icd: "0106", code: "NL:KVK", name: "Vereniging van Kamers van Koophandel en Fabrieken in Nederland"},
    {icd: "9954", code: "NL:OIN", name: "Dutch OverheidsIdentificatieNummer"},
    {icd: "9954", code: "NL:OIN", name: "Dutch Originator's Identification Number"},
    {icd: "0190", code: "NL:OINO", name: "Organisatie Indentificatie Nummer"},
    {icd: "9944", code: "NL:VAT", name: "Netherlands VAT number"},
    {icd: "0192", code: "NO:ORG", name: "The Brønnøysund Register Centre"},
    {icd: "9908", code: "NO:ORGNR", name: "Enhetsregisteret ved Brønnøysundregistrene"},
    {icd: "9909", code: "NO:VAT", name: "Enhetsregisteret ved Brønnøysundregistrene"},
    {icd: "9945", code: "PL:VAT", name: "Poland VAT number"},
    {icd: "9946", code: "PT:VAT", name: "Portugal VAT number"},
    {icd: "9947", code: "RO:VAT", name: "Romania VAT number"},
    {icd: "9948", code: "RS:VAT", name: "Serbia VAT number"},
    {icd: "0007", code: "SE:ORGNR", name: "The Swedish National Tax Board"},
    {icd: "9955", code: "SE:VAT", name: "Swedish VAT number"},
    {icd: "0195", code: "SG:UEN", name: "Singapore Nationwide elnvoice Framework"},
    {icd: "9949", code: "SI:VAT", name: "Slovenia VAT number"},
    {icd: "9950", code: "SK:VAT", name: "Slovakia VAT number"},
    {icd: "9951", code: "SM:VAT", name: "San Marino VAT number"},
    {icd: "9952", code: "TR:VAT", name: "Turkey VAT number"},
    {icd: "0193", code: "UBLBE", name: "UBL.BE"},
    {icd: "9953", code: "VA:VAT", name: "Holy See (Vatican City State) VAT number"},
];

IcdValues.findByIcd = function (icd) {
    return IcdValues.find(x => x.icd === icd);
};

export default IcdValues;